# Generated by Django 4.0.6 on 2022-07-30 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_deals', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_deals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealLots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lots_count', models.PositiveIntegerField()),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='flowers.deal')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='flowers.lot')),
            ],
        ),
    ]
